### ISSUE TITLE
Error operatorPrecedence' from 'pyparsing' - Google Colab

### ISSUE THREAD

**Issue by raulignac10** [rizavelioglu/challenge-aido_RL-IL#15]
Hello @rizavelioglu,

first of all I want to thank you for your repository for those of us who are starting to learn IA in robotics.

I am trying to run google colab but unfortunately there is an error in the pyparsing library, I tried to install the version you used in the execution of your google colab but I could not solve the error.

![Captura de pantalla de 2022-01-22 15-29-09](https://user-images.githubusercontent.com/97913559/150651167-ba41ca61-0f3f-4730-9de4-fd42923627e8.png)

I hope you can help me because your repository is very good to learn.

thank you very much

Raúl

**Comment by rizavelioglu** [comment]
Hello Raúl,
Thank you for your comments!

By the time of writing the notebook (~June 2020), Colab was on `Python3.6` and as of today (January 2022) the default Python version on Colab is `Python3.7`. Therefore, I would guess that the error somehow relates to that. Actually, the Duckietown project owners has faced with this same issue ([see the issue at `duckietown` repo](https://github.com/duckietown/duckietown-shell/issues/63)). One of the creators states in the comments that this is a "dependency error", but sadly the issue was not resolved.

However, I found a workaround! I have updated the notebook such that all dependencies are installed in Python3.6 and the scripts are run in Python3.6. Apparently, everything works!

Hope this helps!
Cheers

**Comment by raulignac10** [comment]
Thank you very much for your help and quick response @rizavelioglu .

I will continue training the duckie by modifying some hyperparameters.

As a last request could you guide me with this last error that occurs when I try to run the test on my local machine.

I have installed the [gym-duckietown](https://github.com/duckietown/gym-duckietown#installation) project and I'm running it through anaconda3 and everything works fine when I run for example basic _control.py

But when I try to run the trained (following the instructions) and with the weights loaded I get the following error:

![Captura de pantalla de 2022-01-23 04-21-59](https://user-images.githubusercontent.com/97913559/150668686-2fa2ac4c-57dd-420e-9f64-6ff2c147c87b.png)

I think I need that library as it doesn't find anything related to Zlogger, I tried to install the same requirements like for example zuper-typing-z5==5.1.1 but it didn't work either.

do you have any idea how i can fix it?

Thank you very much again for your time and help

Best regards

**Comment by raulignac10** [comment]
I was able to solve this error by installing zuper-commons-z6 6.1.7

Thanks again for your help

best regards
